apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/kubernetes/k8id.git
      path: argocd-helm-charts/argo-cd
      targetRevision: postgress_configmap 
        - values.yaml
      helm:
        valueFiles:
          - $values/k8s/microk8s-cluster/argocd-apps/values-argo-cd.yaml
    - repoURL: https://github.com/deepak7340/k8s-config-deepak.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
