apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-helm-charts/keycloak
    repoURL: 'https://github.com/obmondo/k8id.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
