---
keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: 'true'
    - name: KEYCLOAK_USER
      value: "admin"
    # The rest of the list is copied from the obmondo-apps values.yaml,
    # since they are overridden here
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: keycloak-pgsql
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER
      value: "keycloak"
    - name: DB_PASWORD
      value: "sqPKl7mcRDvITHM9El5T2AogQRRDqLrjs9s8tb7im6tIQcQFRZkRsJusGdoYMHIX"
