---
argo-cd:
  dex:
    enabled: false
  repoServer:
    replicas: 2
    autoscaling:
      enabled: false
  configs:
    secret:
      createSecret: false     # managed by sealed-secrets now
  server:
    extraArgs:
      - --insecure
