---
argo-cd:
  dex:
    enabled: false
  repoServer:
    replicas: 2
    autoscaling:
      enabled: false
  configs:
    secret:
      createSecret: false     # managed by sealed-secrets now
  server:
    extraArgs:
      - --insecure
    config:
      repositories:
        - type: git
          url: https://github.com/Obmondo/k8id.git
        - type: git
          url: https://github.com/deepak7340/k8s-config-deepak.git
