---
keycloakx:
  dbchecker:
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: "Keycloak@321"

postgresql:
  enableLogicalBackup: false
  extraEnv: |
    - name: AWS_ACCESS_KEY_ID
      value: "yD4vyTaNiSnLBEuW6g4KsRHO1/D1ebtmVlqQZEUI"
