---
keycloakx:
  dbchecker:
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: "Keycloak@321"
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: >-
            keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: >-
            keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do

postgresql:
  enableLogicalBackup: false
  extraEnv: |
    - name: AWS_ACCESS_KEY_ID
      value: "yD4vyTaNiSnLBEuW6g4KsRHO1/D1ebtmVlqQZEUI"
